### ISSUE TITLE
determiner noun agreement with adjective 1 

### ISSUE THREAD

**Issue by maureendss** [alexwarstadt/data_generation#51]
There seems to be a bug with the `generation_projects/benchmark/determiner_noun_agreement_with_adj_1.py` script, raising an `invalid type promotion` error originating from line 29 : `V1 = choice(all_transitive_verbs)`.
This should be reproducible by simply launching the script with the following command : 
`python -m generation_projects.benchmark.determiner_noun_agreement_with_adj_1`

**Comment by alexwarstadt** [comment]
I wasn't able to reproduce this exact error but I did find an `invalid type promotion` error with line 31: `N2_match = choice(get_matches_of(V1, "arg_2", self.all_pluralizable_nouns))`. I've pushed a change to the vocab which corrects this. Does this fix your problem, or are you still seeing it?

**Comment by maureendss** [comment]
Yes it fixes it, thank you!
